apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr-app-underwater
  labels:
    app: octopus-underwater-app
spec:
  selector:
    matchLabels:
        app: octopus-underwater-app
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: octopus-underwater-app
    spec:
      containers:
        - name: octopus-underwater-app
          image: https://922786934247.dkr.ecr.us-east-1.amazonaws.com/underwater:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          
